import { Table, TableBody, TableCell, TableContainer, TableHead, TableRow } from "@mui/material";
export const LEVELS = ["49.90", "49.70", "49.50"];
export const metricValue = value => value == null ? "—" : typeof value === "number" ? Number(value.toFixed(3)).toLocaleString("en-IN") : value;
const stamp = value => String(value || "").replace("T", " ");
export default function ThresholdPerformanceTable({ rows = [] }) {
  const sticky = { position: "sticky", left: 0, minWidth: 190, maxWidth: 240, bgcolor: "#FFFFFF", zIndex: 2, boxShadow: "1px 0 #DCE9E5" };
  return <TableContainer sx={{ maxHeight: 480, border: "1px solid #DCE9E5", borderRadius: 1 }}><Table size="small" stickyHeader sx={{ minWidth: 1880 }}>
    <TableHead><TableRow><TableCell rowSpan={2} sx={{ ...sticky, bgcolor: "#F1F7F5", zIndex: 5, fontWeight: 850 }}>Entity</TableCell><TableCell rowSpan={2} sx={{ minWidth: 210, bgcolor: "#F1F7F5", fontWeight: 850 }}>Period (IST)</TableCell>{LEVELS.map((level, index) => <TableCell key={level} colSpan={5} align="center" sx={{ bgcolor: ["#FFF7ED", "#FFEDD5", "#FEE2E2"][index], fontWeight: 850 }}>Frequency &lt;{level} Hz</TableCell>)}<TableCell rowSpan={2} sx={{ bgcolor: "#F1F7F5", fontWeight: 850 }}>Lowest Hz</TableCell><TableCell rowSpan={2} sx={{ bgcolor: "#F1F7F5", fontWeight: 850 }}>Messages</TableCell></TableRow>
      <TableRow>{LEVELS.flatMap(level => ["Freq Minutes", "OD/UI Minutes", "OD/UI %", "15-Min Avg OD/UI (MW)", "Max OD/UI (MW)"].map(label => <TableCell key={`${level}-${label}`} sx={{ top: 38, minWidth: 95, bgcolor: "#F8FAFC", fontWeight: 750 }}>{label}</TableCell>))}</TableRow></TableHead>
    <TableBody>{rows.map((row, index) => <TableRow key={`${row.entity_id}-${row.period_start}-${index}`}><TableCell sx={sticky}>{row.entity}</TableCell><TableCell sx={{ fontSize: 11 }}>{stamp(row.period_start)}<br />{stamp(row.period_end)}</TableCell>{LEVELS.flatMap(level => ["frequency_minutes", "adverse_minutes", "adverse_pct", "average_od_ui_mw", "maximum_od_ui_mw"].map(key => <TableCell key={`${level}-${key}`} title={row.thresholds?.[level]?.unknown_deviation_minutes > 0 ? `${metricValue(row.thresholds[level].unknown_deviation_minutes)} frequency minutes have unknown deviation; adverse minutes are observed coverage only.` : undefined} sx={{ fontSize: 12 }}>{metricValue(row.thresholds?.[level]?.[key])}</TableCell>))}<TableCell>{metricValue(row.lowest_frequency)}</TableCell><TableCell>{metricValue(row.message_count)}</TableCell></TableRow>)}{!rows.length && <TableRow><TableCell colSpan={19}>No performance rows for the selected group/period.</TableCell></TableRow>}</TableBody>
  </Table></TableContainer>;
}
