import { useState } from "react";
import { Alert, Box, Button, MenuItem, Stack, Tab, Tabs, TextField, Typography } from "@mui/material";
import dayjs from "dayjs";

export default function DashDemoWorkspace({ workspace, records, events, groups, onSubmit }) {
  const [activity, setActivity] = useState(workspace === "apply-exchange" ? "Exchange" : "Leave");
  const [from, setFrom] = useState(dayjs().add(1, "day").format("YYYY-MM-DD"));
  const [to, setTo] = useState(from);
  const [reason, setReason] = useState("");
  const [notice, setNotice] = useState("");
  const [eventMarked, setEventMarked] = useState(false);
  const [eventBlocked, setEventBlocked] = useState(false);
  const [eventDeadline, setEventDeadline] = useState(dayjs().add(1, "day").format("YYYY-MM-DD"));
  if (workspace === "special-event") return <Stack spacing={2}><Alert severity="info">Sample Special Event roster. Announce the event first; blocking leave is a separate action. Live administrators may select all or specific departments, and HODs manage their own departments.</Alert><Typography fontWeight={800}>Special operations period</Typography><TextField type="date" label="Event from" value={from} onChange={e=>setFrom(e.target.value)} InputLabelProps={{ shrink: true }} /><TextField type="date" label="Last application submission" value={eventDeadline} onChange={e=>setEventDeadline(e.target.value)} InputLabelProps={{ shrink: true }} /><Typography>Operations department | {from} to {dayjs(from).add(3,"day").format("YYYY-MM-DD")}</Typography>{!eventMarked ? <Button variant="contained" onClick={()=>setEventMarked(true)}>Mark special event</Button> : <><Alert severity={eventBlocked ? "warning" : "success"}>Event announced. Last application submission: {eventDeadline}. {eventBlocked ? "No leave application in this period" : "Leave applications remain open"}</Alert><Button onClick={()=>setEventBlocked(value=>!value)}>{eventBlocked ? "Reopen leave" : "Block leave"}</Button></>}{groups.map(group => <Box key={group.groupName} sx={{ p: 2, bgcolor: "#F5F7F9", borderRadius: 2 }}><Typography fontWeight={800}>{group.groupName} | Sample staffing</Typography><Typography variant="body2">{group.employees.map(person=>person.name).join(", ")}</Typography></Box>)}</Stack>;
  if (workspace === "apply" || workspace === "apply-exchange" || workspace === "replacement") return <Stack spacing={2}>
    <Alert severity="info">Sample data preview. Changes stay in this page until it is reloaded.</Alert>
    {notice && <Alert severity="success">{notice}</Alert>}
    {workspace === "apply" && <Tabs value={activity} onChange={(_, value) => setActivity(value)} variant="scrollable">{["Leave", "Training", "Sports", "Exchange"].map(kind => <Tab key={kind} value={kind} label={kind} />)}</Tabs>}
    <Typography sx={{ fontWeight: 800 }}>{workspace === "replacement" ? "Assign duty coverage" : `New ${activity.toLowerCase()} application`}</Typography>
    {workspace === "replacement" && <><TextField select label="Duty" defaultValue="Morning"><MenuItem value="Morning">Morning</MenuItem><MenuItem value="Evening">Evening</MenuItem><MenuItem value="Night">Night</MenuItem></TextField><TextField select label="Replacement employee" defaultValue="Priya Das">{groups[0].employees.map(person => <MenuItem key={person.employeeId} value={person.name}>{person.name}</MenuItem>)}</TextField></>}
    <Stack direction={{ xs: "column", sm: "row" }} spacing={2}><TextField fullWidth type="date" label="From" value={from} onChange={event => { setFrom(event.target.value); if (event.target.value > to) setTo(event.target.value); }} InputLabelProps={{ shrink: true }} /><TextField fullWidth type="date" label="To" value={to} inputProps={{ min: from }} onChange={event => setTo(event.target.value)} InputLabelProps={{ shrink: true }} /></Stack>
    <TextField label="Reason / remarks" multiline minRows={2} value={reason} onChange={event => setReason(event.target.value)} />
    <Button variant="contained" disabled={!from || !to || to < from} onClick={() => { onSubmit({ kind: workspace === "replacement" ? "Replacement" : activity, date: from, startDate: from, endDate: to, reason }); setNotice("Saved in this sample preview. Open Tracking or History to see the new record."); }}>Save sample {workspace === "replacement" ? "replacement" : "application"}</Button>
  </Stack>;
  if (workspace.includes("view=events")) return <Stack spacing={1.4}>{events.map(event => <Box key={event.id} sx={{ p: 2, borderRadius: 2, bgcolor: { holiday: "#FDEEF0", training: "#F1EDFC", sports: "#EDF7F2" }[event.kind] }}><Typography fontWeight={800}>{event.title}</Typography><Typography variant="body2">{event.startDate} – {event.endDate}</Typography><Typography variant="caption">{event.detail}</Typography></Box>)}</Stack>;
  if (workspace.includes("operations")) return <Stack spacing={1.5}><Alert severity="info">Sample approval inbox for a reporting officer.</Alert>{records.filter(row => /pending|applied/i.test(row.finalStatus || row.status || "")).map(row => <Box key={row.id} sx={{ p: 2, bgcolor: "#FFF8E5", borderRadius: 2 }}><Typography fontWeight={800}>{row.kind} · {row.employeeName || row.name || row.firstEmployee?.name}</Typography><Typography variant="body2">{row.startDate || row.date}</Typography><Button onClick={() => setNotice(`Sample ${row.kind.toLowerCase()} approval selected.`)}>Review approval</Button></Box>)}{notice && <Alert severity="success">{notice}</Alert>}</Stack>;
  if (workspace.includes("calendar")) return <Stack spacing={2}><Alert severity="info">The dashboard shows the complete sample roster for D−1 through D+7. Close this window to explore the shift cells.</Alert>{groups.map(group => <Box key={group.groupName}><Typography fontWeight={800}>{group.groupName}</Typography><Typography variant="body2">{group.employees.map(person => person.name).join(" · ")}</Typography></Box>)}</Stack>;
  return <Stack spacing={1.5}><Alert severity="info">Sample application details</Alert>{records.filter(row => workspace.includes(row.kind.toLowerCase()) || workspace.includes("replacement") && ["Exchange", "Replacement"].includes(row.kind)).map(row => <Box key={row.id} sx={{ p: 2, bgcolor: "#F5F7F9", borderRadius: 2 }}><Typography fontWeight={800}>{row.kind} · {row.employeeName || row.name || row.firstEmployee?.name}</Typography><Typography variant="body2">{row.startDate || row.date} · {row.finalStatus || row.status}</Typography></Box>)}</Stack>;
}
