import { useEffect, useState } from "react";
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Paper, Stack, TextField, Typography } from "@mui/material";
import api from "../../crewLegacy/api";
import LeaveBlockedPeriods from "./LeaveBlockedPeriods";
const blank = { title: "", reason: "", startDate: "", endDate: "", submissionDeadline: "", departmentIds: [] };
export default function SpecialEventRoster() {
  const [access, setAccess] = useState(null), [events, setEvents] = useState([]), [open, setOpen] = useState(false), [form, setForm] = useState(blank), [error, setError] = useState(""), [busy, setBusy] = useState(false), [decision, setDecision] = useState(null), [staffing, setStaffing] = useState(null);
  const load = async () => { try { const [a,e] = await Promise.all([api.get("/special-events/access"), api.get("/special-events")]); setAccess(a.data); setEvents(Array.isArray(e.data) ? e.data : []); } catch(e) { setError(e.response?.data?.detail || "Could not load special events"); } };
  useEffect(() => { load(); }, []);
  const save = async () => { setBusy(true); setError(""); try { if (decision) await api.put(`/special-events/${decision.id}/blocking`, { blocked: !decision.leaveBlocked }); else await api.post("/special-events", form); setOpen(false); setDecision(null); setForm(blank); await load(); window.dispatchEvent(new Event("crew-special-events-changed")); } catch(e) { setError(e.response?.data?.detail || "Could not save event"); } finally { setBusy(false); } };
  return <Paper sx={{ p: 2, mb: 2, borderRadius: "20px !important", background: "#FFF !important", boxShadow: "0 8px 28px #54448A0B" }}><Stack direction="row" justifyContent="space-between" alignItems="center"><Box><Typography fontWeight={850} fontSize={19}>Plan event coverage</Typography><Typography variant="body2" color="text.secondary">Announce first. Block leave separately for the chosen departments.</Typography></Box>{access?.canManage && <Button variant="contained" sx={{ borderRadius: "12px !important", bgcolor: "#5C43DC !important", textTransform: "none", whiteSpace: "nowrap" }} onClick={() => { setForm({ ...blank, departmentIds: access.allowAll ? [] : access.departments.map(d=>d.id) }); setOpen(true); }}>Mark special event</Button>}</Stack>{error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
  <Stack spacing={1.3} sx={{ mt: 2 }}>{events.map(event => <Box key={event.id} sx={{ p: 2, bgcolor: event.leaveBlocked ? "#FFF3DF" : "#F0EDFF", borderRadius: 3 }}><Typography fontWeight={850}>{event.title} <Chip size="small" label={event.leaveBlocked ? "Leave blocked" : "Announced"} /></Typography><Typography variant="body2">{event.startDate} to {event.endDate} | {event.departmentNames?.join(", ") || "All departments"}</Typography>{event.submissionDeadline && <Typography variant="body2">Last application submission: {event.submissionDeadline}</Typography>}<Typography variant="body2">{event.leaveBlocked ? "No leave application in this period" : "Leave applications remain open"}</Typography>{event.reason && <Typography variant="body2">{event.reason}</Typography>}{event.canManage && <Stack direction="row" spacing={1} sx={{ mt: 1 }}><Button color="warning" onClick={() => setDecision(event)}>{event.leaveBlocked ? "Reopen leave" : "Block leave"}</Button><Button onClick={async () => { try { setStaffing((await api.get(`/special-events/${event.id}/staffing`)).data); } catch(e) { setError(e.response?.data?.detail || "Could not load staffing"); } }}>Staffing view</Button></Stack>}</Box>)}</Stack>
  <Dialog open={open || Boolean(decision)} onClose={() => !busy && (setOpen(false),setDecision(null))} fullWidth maxWidth="sm" slotProps={{ paper: { sx: { borderRadius: "24px !important", p: 1, background: "#FAF9FF !important" } } }}><DialogTitle>{decision ? decision.leaveBlocked ? "Reopen leave applications?" : "Block leave for this event?" : "Mark special event"}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}>{error && <Alert severity="error">{error}</Alert>}{decision ? <Alert severity="warning">{decision.title}: {decision.startDate} to {decision.endDate}. {decision.departmentNames?.join(", ") || "All departments"}. Existing applications are unchanged.</Alert> : <><Alert severity="info">Marking announces the event. It does not block leave until you choose Block leave.</Alert><TextField label="Event name" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} /><Stack direction="row" spacing={1}>{["startDate","endDate"].map(key=><TextField key={key} fullWidth type="date" label={key==="startDate" ? "Event from" : "Event through"} InputLabelProps={{shrink:true}} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})} />)}</Stack><TextField type="date" label="Last application submission (optional)" InputLabelProps={{shrink:true}} value={form.submissionDeadline} onChange={e=>setForm({...form,submissionDeadline:e.target.value})} /><TextField select label="Departments" SelectProps={{ multiple:true, displayEmpty:true, renderValue:values=>values.length ? access.departments.filter(d=>values.includes(d.id)).map(d=>d.name).join(", ") : "All departments" }} InputLabelProps={{shrink:true}} value={form.departmentIds} onChange={e=>setForm({...form,departmentIds:e.target.value})}>{access?.departments.map(d=><MenuItem key={d.id} value={d.id}>{d.name}</MenuItem>)}</TextField>{access?.allowAll && <Button onClick={()=>setForm({...form,departmentIds:[]})}>All departments</Button>}<TextField label="Announcement note" multiline value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} /></>}</Stack></DialogContent><DialogActions><Button disabled={busy} onClick={()=>{setOpen(false);setDecision(null);}}>Cancel</Button><Button disabled={busy || (!decision && (!form.title.trim() || !form.startDate || !form.endDate || form.endDate < form.startDate || (!access?.allowAll && !form.departmentIds.length)))} variant="contained" onClick={save}>{busy ? "Saving..." : decision ? "Confirm" : "Announce event"}</Button></DialogActions></Dialog>
  <Dialog open={Boolean(staffing)} onClose={()=>setStaffing(null)} fullWidth maxWidth="lg"><DialogTitle>Special Event staffing</DialogTitle><DialogActions><Button onClick={async () => { try { const response = await api.get(`/leave/blocked-periods/${staffing.id}/staffing.xlsx`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const a = document.createElement("a"); a.href = url; a.download = "special_event_staffing.xlsx"; a.click(); URL.revokeObjectURL(url); } catch(e) { setError(e.response?.data?.detail || "Could not export staffing"); } }}>Download Excel</Button></DialogActions><DialogContent>{staffing && <Stack spacing={2}>{["shifts","leaveShifts","replacementShifts"].map((key,index)=><Box key={key}><Typography fontWeight={850}>{["Duty strength","Employees on leave","Replacement employees"][index]}</Typography>{staffing.dates.map(date=><Box key={date} sx={{ p:1, borderBottom:"1px solid #DDD" }}><Typography fontWeight={750}>{date} {staffing.dayNames[date]}</Typography>{["Morning","Evening","Night"].map(shift=><Typography key={shift} variant="body2">{shift}: {staffing[key]?.[shift]?.[date]?.map(p=>p.name).join(", ") || "NR"}</Typography>)}</Box>)}</Box>)}</Stack>}</DialogContent></Dialog>
  {access?.allowAll && <Box sx={{ mt: 2 }}><LeaveBlockedPeriods isAdmin allowCreate={false} /></Box>}
  </Paper>;
}
